const appConfiguration = {
    ONE_SIDED_POTENTIAL_PARTNER_COUNT_MAXIMUM: 8,
    ONE_SIDED_POTENTIAL_PARTNER_COUNT_MINIMUM: 4,
    ONE_SIDED_COMPETITOR_COUNT: 0,
    TWO_SIDED_POTENTIAL_PARTNER_COUNT_MAXIMUM: 8,
    TWO_SIDED_POTENTIAL_PARTNER_COUNT_MINIMUM: 4,
    TWO_SIDED_COMPETITOR_COUNT_MAXIMUM: 7,
    TWO_SIDED_COMPETITOR_COUNT_MINIMUM: 3,
}

module.exports = {appConfiguration}